config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/' => 'pages#home'

  resources :products
  get 'products/:id/delete' => 'products#delete', :as => :products_delete

  resources :categories
   get 'categories/:id/delete' => 'categories#delete', :as => :categories_delete

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end

  def new
     @category = Category.new
  end
  def create
  @category = Category.new(category_params)
    if @category.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])
    if @category.update_attributes(category_params)
      redirect_to(:action => 'show', :id => @category)
    else
      render('index')
    end
  end

  def delete
    @category = Category.find(params[:id])
  end
  def destroy
    Category.find(params[:id]).destroy
    redirect_to(:action => 'index')
  end
  private
  def category_params
    params.require(:category).permit(:name, :thumburl)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
	
	def render_demo
		render :home
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end
  def edit
    @product = Product.find(params[:id])
  end
  def update
  @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      redirect_to(:action => 'show', :id => @product.id)
    else
      render('index')
    end
end

  def delete
    @product = Product.find(params[:id])
  end
  def destroy
 Product.find(params[:id]).destroy
 redirect_to(:action => 'index')
end
  
  private
  def product_params
  	params.require(:product).permit(:product_name, :description, :price, :thumburl)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>

  <div class="name">
  <%=f.label :name %></br>
  <%=f.text_field :name %>
  </div>
  <div class="thumburl">
  <%=f.label :thumburl %></br>
  <%=f.url_field :thumburl %>
  </div>
  <div class="actions">
  <%= f.submit %>
  </div>
<% end %>

app/views/categories/delete.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Thumburl:</strong>
  <%= @category.thumburl %>
</p>

<%= link_to "Delete", categories_delete_path(:id => @category.id) %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="categories">
      <div class="container">
        <div class="row">
          <div class="col-md-2">
            <h2>Categories</h2>
            <p>Explore our latest categories from around the world.</p>
          </div>
          <div class="col-md-8">
            <% @categories.in_groups_of(3).each do |categories| %>
              <% categories.select! {|x| !x.nil?} %>
              <div class='row'>
                <% categories.each do |category| %>
                  <div class='col-md-4'>
                    <div class="thumbnail">
                        <img src= <%= category.thumburl %> >
                        <div class="caption">
                          <span class="listing-title"><%= category.name %></span>
                          <span><%= link_to "Edit", edit_category_path(category.id) %></span>
                          <span><%= link_to 'Show', category %></span>
                          <td><%= link_to 'Delete', categories_delete_path(:id => category.id) %></td>
                        </div>
                      </div>
                    </div>
                <% end %>
              </div>
            <% end %>

          </div>
        </div>

      </div>
    </div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Thumburl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.thumburl %></td>
        <td><%= link_to 'Show', category_path(category) %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

  <!-- <table>
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <div class="thumbnail">
           <img src= <%=category.thumburl %> >
        <div>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', categories_delete_path(:id => category.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Category', new_category_path %>
 -->

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1>Listing products</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Thumburl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <% if product.thumburl %>
          <%= product.thumburl %>
        <% end %>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EasyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<body>
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h1>Shop directly from people around the world.</h1>
      </div>
    </div>
  </div>
</div>

<div class="trending">
  <div class="container">
    <h2>Recent Favorites</h2>
    <p>Discover finds from around the marketplace.</p>
    <div class="row trending-listing">
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/034/0/6705395/il_340x270.542888787_ggy4.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$100.00</span>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/010/0/6957353/il_340x270.427320275_pxiv.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$15.00</span>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="thumbnail">
          <img src="https://img1.etsystatic.com/038/0/6566540/il_340x270.566511947_1r1t.jpg">
          <div class="caption">
            <span class="listing-title">Large gold leather bag</span>
            <span class="listing-price">$160.00</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

app/views/products/ _form.html.erb
<%= form_for(@product) do |f| %>

  <div class="product_name">
  <%=f.label :name %></br>
	<%= f.text_field :product_name %><br>
  </div>
  <div class="description">
    <%=f.label :description %></br>
    <%= f.text_field :description %>
  </div>
  <div class="price">
  <%=f.label :price %></br>
  <%= f.text_field :price %>
  </div>
  <div class="thumburl">
  <%=f.label :thumburl %></br>
  <%= f.url_field :thumburl %>
  </div>
  <div class="actions">
  <%= f.submit %>
  </div>
<% end %>



  

app/views/products/delete.html.erb
<!-- <h1>Products#delete</h1>
<p>Find me in app/views/products/delete.html.erb</p> -->

<p>
  <strong>Product name:</strong>
<%= @product.product_name %>
</p>

<p>
  <strong>Description:</strong>
	 <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
<%= @product.price %>
</p>

<p>
  <strong>Thumburl:</strong>
<%= @product.thumburl %>
</p>

<%= link_to 'Delete', products_delete_path(:id => @product.id) %> |
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/edit.html.erb
<!-- <h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p> -->

<h1>Edit Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Thumburl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.product_name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <% if product.thumburl %>
          <%= product.thumburl %>
        <% end %>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>


<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<!-- <h1>Products#show</h1>
<p>Find me in app/views/products/show.html.erb</p> -->
<p>
  <strong>Product name:</strong>
  <%= @product.product_name %>

</p>

<p>
  <strong>Description:</strong>
<%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
<%= @product.price %>
</p>

<p>
  <strong>Thumburl:</strong>
<%= @product.thumburl %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>